# Setup
title:               Trapa
tagline:             'test'
description:         '-'
url:                 http://trapa-eureka.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              JINHO SON
  url:               -
  email:             1982gaya@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
