# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          JINHO SON
baseurl:        ""
url:            "http://trapa-eureka.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         JINHO SON
  url:          http://trapa-eureka.github.io
  email:        1982gaya@gmail.com  
  github:       Trapa-Eureka
  twitter:      

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/Trapa-Eureka/trapa-eureka.github.io