title: Trapa
author: Trapa
email: your-email@domain.com
remote_theme: thelehhman/plainwhite-jekyll
description: > # this means to ignore newlines until "show_exerpts:"
  test
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: JINHO SON
  tagline: Python, Django, ES6, Tailwind CSS, etc
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  disqus_shortname: games
  analytics_id: "UA-165438498-1"
  sitemap: true
  # generate social links in footer

  # navigation:
  #   - title: test1
  #     url: "/test1"
  #   - title: test2
  #     url: "/test2"

  social_links:
    twitter: 
    github:  Trapa-Eureka
    linkedIn: in/jinho-son-10a08167
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
